### PR TITLE
adding more functionalities

### PR DESCRIPTION
**Pull request by emanuelgsouza**
This PR adds the following three new functionalities:

* Add more HTTP methods to the `explore/*` route: `put`, `delete` and `post`
* Refresh token automatically
* A new route to get user information (`/auth/user`)

### CODE REVIEW

**Comment by emanuelgsouza** [comment]
> @emanuelgsouza changes looks good. Do you update also Readme.md file please? Or should I?

Yes, I can update

**Comment by onefriendaday** [comment]
Could you also please add semantic-version to automatically release the version? Thanks!

**Comment by emanuelgsouza** [comment]
> Could you also please add semantic-version to automatically release the version? Thanks!

@onefriendaday the `semantic-release` has been configured.

Like described [in the documentation](https://semantic-release.gitbook.io/semantic-release/usage/installation), it's a good practice specify the semantic-release version even executed globally. So, I chose the last version (v.17) to execute.

Lastly, I made a test locally and the generated version will be `v1.0.0`.

**Pull request merged**
